name: Lint inputted url

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'Repository url'
        required: true
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: actions/checkout@main
        
      - name: Lint
        uses: ./action


